# Site settings
title: Leyla Abdullayeva
email: leyla.violetta05@gmail.com
url: https://github.com/leyviya/leyviya.github.io
description: " Hi! I'm Leila, an ambitious tech enthusiast from Baku, Azerbaijan, studying in Istanbul, Turkey. I'm a senior year Computer Engineering student at Beykoz University. My main interest field is Machine Learning, AI, and Data Analytics. I've developed many programming projects based on Python during my internships and university period.
keywords: "software, tech"
skills: "Computer/Software Engineer - Tech Enthusiast - AI Nerd"
lang: "en, azerbaijani, turkish"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: leyviya♥︎
  location: Turkey
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/leyviya/
  - title: facebook
    url: https://www.facebook.com/leyla.abdullayeva.56808
  - title: stack-overflow
    url: https://stackoverflow.com/users/14976891/leyviya
  - title: linkedin
    url: https://www.linkedin.com/in/leyla-abdullayeva-557138197/
  - title: github
    url: http://github.com/leyviya

# Postal address (add as many lines as necessary)
address:
  - line: Sancaktepe
  - line: Istanbul

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
