# Site settings
title: Leyla Abdullayeva
email: leyla.violetta05@gmail.com
url: https://github.com/leyviya/leyviya.github.io
description: " Hi! I'm Leila, an ambitious tech enthusiast from Baku, Azerbaijan, studying in Istanbul, Turkey. I'm a senior year Computer Engineering student at Beykoz University. My main interest field is Machine Learning, AI, and Data Analytics."
keywords: "software, tech"
skills: "Computer Engineer / Software Developer - Tech Enthusiast - AI Nerd"
lang: "english, azerbaijani, turkish"
meta_author: LastName FirstName

# Google webmaster tools
google_verify: "https://search.google.com/google-site-verification:googled9587bd991abb2a6.html"

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: c8a2c8 #80B3FF
  primary-rgb: "200,162,200" #"128,179,255"
  secondary: 600080 #FD6E8A
  secondary-dark: 270034 #A2122F

# Footer settings
footer:
  copyright: leyviya♥︎
  location: Location
  social: Contact Profiles
  credits: Around The Web 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/leyviya
  - title: bitbucket
    url: https://bitbucket.org/leylaabdullayeva/
  - title: linkedin
    url: https://www.linkedin.com/in/leyla-abdullayeva-557138197/
  - title: instagram
    url: https://www.instagram.com/leyviya/
  - title: facebook
    url: https://www.facebook.com/leyla.abdullayeva.56808

# Postal address (add as many lines as necessary)
address:
  - line: Istanbul, Turkey. 🇹🇷
  - line: Baku, Azerbaijan. 🇦🇿

# Linktr.ee content
credits : 'You can find all my social and professional web profile links from <a href="https://linktr.ee/leyviya">Linktr.ee</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
      values:
      permalink: ""
